### ISSUE TITLE
SVG to DXF etc?

### ISSUE THREAD

**Issue by zezba9000** [ixmilia/converters#9]
Did you have a converter from SVG to DXF?
Looks like no.

I'm using vtracer to get a SVG from a PNG. Now I need to get a DXF from a SVG.
https://github.com/visioncortex/vtracer

**Comment by brettfo** [comment]
I currently have no plans to create an SVG->* converter.  The simple cases, e.g., `<line x1="..." y1="..." x2="..." y2="..." />` are easy enough to handle, but each element and each group can have its own transform element which can make it really complicated really fast, and if I can't provide a reasonable experience for each file I'd rather not do it at all.

It's essentially why I don't plan on making a PDF->DXF converter, either; too many open-ended questions with no reasonable answer.

**Comment by zezba9000** [comment]
No worries. I'll just invoke Inkscape with command line args to run conversions.
